language: "en"

enabled: true
players:
  enabled: true
  require-empty-hand: false
  sit-height: 1.0
  blocked-worlds:
    - "SOME_CUSTOM_DISABLED_WORLD"

blocks:
  enabled: true
  require-empty-hand: false
  right-click: true
  left-click: false
  blocked-worlds:
    - "SOME_CUSTOM_DISABLED_WORLD"
  blocks:
    - STAIR
    - CARPET
    - SLAB

crawl:
  enabled: true
  require-empty-hand: false
  blocked-worlds:
    - "SOME_CUSTOM_DISABLED_WORLD"
  stop-on-jump: true
  stop-on-sneak: true
  stop-on-damage: true
  stop-on-vertical-movement: true
