language: "en"

enabled: true
players:
  enabled: true
  blocked-worlds:
    - "SOME_CUSTOM_DISABLED_WORLD"

blocks:
  enabled: true
  require-empty-hand: false
  right-click: true
  left-click: false
  blocked-worlds:
    - "SOME_CUSTOM_DISABLED_WORLD"
  blocks:
    - STAIR
    - CARPET
    - SLAB
